# Generated by Django 5.2.1 on 2025-05-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalrecommendation',
            name='score',
            field=models.FloatField(help_text='Compatibility score between 0 and 1'),
        ),
    ]
