# Generated by Django 5.2.1 on 2025-05-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_alter_animalrecommendation_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalrecommendation',
            name='score',
            field=models.FloatField(help_text='Match score between 0 and 1'),
        ),
    ]
