# Generated by Django 5.2.1 on 2025-05-14 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_alter_animalviewhistory_options_and_more'),
        ('recommendations', '0003_alter_animalrecommendation_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animalrecommendation',
            name='interaction_score',
            field=models.FloatField(default=0.0, help_text="Score based on user's viewing history"),
        ),
        migrations.AddField(
            model_name='animalrecommendation',
            name='preference_score',
            field=models.FloatField(default=0.0, help_text="Score based on user's explicit preferences"),
        ),
        migrations.AddField(
            model_name='animalrecommendation',
            name='reason',
            field=models.CharField(blank=True, help_text='Reason for recommendation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='animalrecommendation',
            name='similarity_score',
            field=models.FloatField(default=0.0, help_text='Score based on content similarity'),
        ),
        migrations.AddIndex(
            model_name='animalrecommendation',
            index=models.Index(fields=['user', 'score'], name='recommendat_user_id_c27e2b_idx'),
        ),
    ]
