# Generated by Django 5.2.1 on 2025-05-14 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_animalrecommendation_interaction_score_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='animalrecommendation',
            name='recommendat_user_id_c27e2b_idx',
        ),
        migrations.RemoveField(
            model_name='animalrecommendation',
            name='reason',
        ),
    ]
