# Generated by Django 5.2.1 on 2025-05-14 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_animal_energy_level_animal_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalviewhistory',
            options={},
        ),
        migrations.AlterField(
            model_name='animalviewhistory',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to='animals.animal'),
        ),
        migrations.AlterField(
            model_name='animalviewhistory',
            name='species',
            field=models.CharField(blank=True, default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animalviewhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='animalviewhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='animalviewhistory',
            name='view_duration',
            field=models.IntegerField(default=0, help_text='View duration in seconds'),
        ),
        migrations.AddIndex(
            model_name='animalviewhistory',
            index=models.Index(fields=['user', '-timestamp'], name='animals_ani_user_id_b0f790_idx'),
        ),
        migrations.AddIndex(
            model_name='animalviewhistory',
            index=models.Index(fields=['user', 'species'], name='animals_ani_user_id_357663_idx'),
        ),
    ]
