# Generated by Django 5.2.1 on 2025-05-14 23:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_alter_animalviewhistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalviewhistory',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Animal view histories'},
        ),
        migrations.RemoveIndex(
            model_name='animalviewhistory',
            name='animals_ani_user_id_b0f790_idx',
        ),
        migrations.RemoveIndex(
            model_name='animalviewhistory',
            name='animals_ani_user_id_357663_idx',
        ),
        migrations.AlterField(
            model_name='animalviewhistory',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animal'),
        ),
        migrations.AlterField(
            model_name='animalviewhistory',
            name='species',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animalviewhistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='animalviewhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='animalviewhistory',
            name='view_duration',
            field=models.IntegerField(default=0, help_text='Duration of view in seconds'),
        ),
    ]
