# Generated by Django 5.2.1 on 2025-05-12 10:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_animalviewhistory'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='has_children',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='has_other_cats',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='has_other_dogs',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_age_max',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_age_min',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_animal_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 12, 10, 26, 4, 115694, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('VIEW', 'Viewed Profile'), ('LIKE', 'Liked Animal'), ('SAVE', 'Saved Animal'), ('INQUIRY', 'Made Inquiry'), ('ADOPT', 'Initiated Adoption')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='animals.animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_type', models.CharField(choices=[('HOUSE', 'House'), ('APT', 'Apartment'), ('CONDO', 'Condominium'), ('OTHER', 'Other')], default='HOUSE', max_length=10)),
                ('has_yard', models.CharField(choices=[('NONE', 'No Yard'), ('SMALL', 'Small Yard'), ('MEDIUM', 'Medium Yard'), ('LARGE', 'Large Yard')], default='NONE', max_length=10)),
                ('has_children', models.BooleanField(default=False)),
                ('has_other_dogs', models.BooleanField(default=False)),
                ('has_other_cats', models.BooleanField(default=False)),
                ('preferred_species', models.CharField(blank=True, max_length=50)),
                ('min_age_months', models.PositiveIntegerField(default=0)),
                ('max_age_months', models.PositiveIntegerField(default=240)),
                ('preferred_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'Any')], default='A', max_length=1)),
                ('activity_level_preference', models.IntegerField(default=3, help_text='Preferred activity level from 1 to 5')),
                ('training_level_preference', models.IntegerField(default=3, help_text='Preferred training level from 1 to 5')),
                ('is_first_time_owner', models.BooleanField(default=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='animal_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
